name: 打包部署

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      Docker_Image_Name: happydang/short-link
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: docker-build
      run: |
        tag=$(date +%s)
        docker build . --file Dockerfile --tag $Docker_Image_Name:${tag}
        echo "::set-output name=tag::${tag}"

    - name: login docker hub
      run: docker login -u happydang -p happydang1215
    - name: push docker hub
      run: |
        echo 当前仓库名为：$GITHUB_REPOSITORY
        echo 这是key：$DEPLOY_KEY
        docker push $Docker_Image_Name:${{steps.docker-build.outputs.tag}}

    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: "101.42.163.104"
        key: "
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAsaX55BvPA2CtbtsIT+4VDU0/Rr5euf8DdXt0ZJsMjDnsXC6N2R8L
E/lLxH2MIRJuVKqTawByERXon35eXonP8swhbv6ntnuaWy6b9D/4Z5ai2+AqS3KXcR3B5C
Rkkl8dC3qmewaokhR4iPpUwkzTR16W7qMfK9xYOWJd6zNay9igTPUvRSPIlWrb3jVVPjYL
NmcDc2K0MSxCS6qiOagwNQNkFlBTMwbWFqueHTbz2W1HyO0Nz2HQkajFVpHbQsh4det438
nJsdnj+kx7o8WikpWdo87iVJKNdhHSRryP8ODIIJ4FB72+hS1YDG9LgC97aPrAiVGEURZt
kLAxsbUq6skrdUtYPegi1dApyMoHGhqf2YjkFWULXmlDvo2r0e1ynvv5GUMEFNtWYeAeIR
e93oaVNAJoeUzzbydgRLt9wO4rFQctVsC15ktU23xzyCF1STMz/943miU4JsVZV+IRwPpB
gvX+FfB8Jv0pRje/fLUzDtwT4G+WZ0vP25GyWGT/AAAFkCYYACUmGAAlAAAAB3NzaC1yc2
EAAAGBALGl+eQbzwNgrW7bCE/uFQ1NP0a+Xrn/A3V7dGSbDIw57FwujdkfCxP5S8R9jCES
blSqk2sAchEV6J9+Xl6Jz/LMIW7+p7Z7mlsum/Q/+GeWotvgKktyl3EdweQkZJJfHQt6pn
sGqJIUeIj6VMJM00delu6jHyvcWDliXeszWsvYoEz1L0UjyJVq2941VT42CzZnA3NitDEs
QkuqojmoMDUDZBZQUzMG1harnh0289ltR8jtDc9h0JGoxVaR20LIeHXreN/JybHZ4/pMe6
PFopKVnaPO4lSSjXYR0ka8j/DgyCCeBQe9voUtWAxvS4Ave2j6wIlRhFEWbZCwMbG1KurJ
K3VLWD3oItXQKcjKBxoan9mI5BVlC15pQ76Nq9Htcp77+RlDBBTbVmHgHiEXvd6GlTQCaH
lM828nYES7fcDuKxUHLVbAteZLVNt8c8ghdUkzM//eN5olOCbFWVfiEcD6QYL1/hXwfCb9
KUY3v3y1Mw7cE+BvlmdLz9uRslhk/wAAAAMBAAEAAAGAFP3HyWx/yaZi1/aJxOgdFLVMBM
/54YCAqCEuX7Tyhp9RjpLxr/Y7GOEcUtuC82V6JAcD5GDpGZu9IRuNix49tDLqwHLW3nk8
hAm9496rO5JRLCoQ1Vl1C6i4gHzMZX9Xr0OO6Hqg8KH6nDT4Tv1E+enza79ar5QZ2K4G6w
Pmdq/iQTW3oDPaP82grWEf8XnxWTxS7A99u1G/g7Fl+eolyB3edcSIED9+jK86v7j+l3KS
SOu59gdY3d1TdCdIAVwurVmF3Xaj6NAqDc6vdcv7KHpy3N7WZm7H5Ga761877Ul3YGLkkx
0UlHrYhzOo9Fju9gOJx0MyfHNq0/UvdXljkRC3vJA2uqpbcR3nAZSU+96OnylNntumJWfi
R+xPYT8NNDvhIuMhV2HLK4rgYQinzSrW3vlNTluOCGy6+m6oiZXldD8rHPEyeVbwUppslu
mDCaeIhvseMPxhrps+LiQFAQj/PQ+spvMyIfcWb+kIL64YlialDg/mafpRlkVXH4YBAAAA
wFR9FajZYQLQD0p0ujwof0OzIS1995LbAIM4YYweTGRS6qhavOIjPi/4wKcIPD4mwsZPiD
jfxdbO/LoFGkbFJOT0pjKlqVuPCEg3qIHQnCcvmwgDRG1TN9YBEZ/qfXayCXKiJsFBNwfL
fCyBdF91tXTpF9pZhWeQ8aIM0Ke1VS9IbdDhhnyfciF9Xf8CMHDzFR2y+DgFv9rg8rR66J
P3K+qOP6GeRz/otzVZmXVdMv9NNAUsybAJy5JZ34sZ4ujbzQAAAMEA18ya8UKWIIy9AQzg
BU57YCZnrM8YuGnUyskT4zPSLSKKYLPmJHPN/UKVDkHfiomXqpRBNPTMIB44fWbo8lILur
vDCex66RrJp1olfjtAKta9jO3LZt98lw6osk39zQG6wn1SA6tIbgeS0++sWdXIhZAz2zHl
m7ojpvKulj6pp27OJDsE59nADsJdkcI36mciEJbGCJi69YCuyP58m9u38uPzTBDtXq4yGw
fUDbYLkGXmfOhOcRk/TB1QxyD+BVDrAAAAwQDSvfeePzjf+gQhr9SYRN+lBqM14paorphM
puHB19a9N71siKJkSr47PebkYtaJr00I5XJHPTDMR044T4SxV7csNVC1KEbBuZODTyL8bC
4PaZ6sFFOmz3Efv+e/meJ2sQ8Ggi1448IuIOcUnYm3F1ouCDrwnEVBxsQDnl3f41eHkNlu
h2s016QKAC8J5rC26iDeWCBDUPPHuzEzkH03uH6pqEeqw/Nn7NT7ySeAdUUW8e9WvOvkEO
ctJBCD0IatFz0AAAAVMTg3OTJAREVTS1RPUC1NRDYyTzZBAQIDBAUG
-----END OPENSSH PRIVATE KEY-----
"
        username: "ubuntu"
        script: |
          pwd
