name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: docker-build
      run: |
        tag=$(date +%s)
        docker build . --file Dockerfile --tag happydang/my-image-name:${tag}
        echo "::set-output name=tag::${tag}"

    - name: login docker hub
      run: docker login -u happydang -p happydang1215
    - name: push docker hub
      run: |
        echo 当前仓库名为：$GITHUB_REPOSITORY
        echo 当前操作者为：${{<$GITHUB_REPOSITORY>}}
        echo 当前tag为：${{steps.docker-build.outputs.tag}}
        docker push happydang/my-image-name:${{steps.docker-build.outputs.tag}}
